version: "3.8"

services:
  db:
    image: "postgres:14.4-alpine"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - ping-network

networks:
  ping-network:
    name: ping-network
    external: false

volumes:
  db:
    driver: local